on:
  push:
    branches:
      - develop

jobs:
  upgrade_to_Python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Upgrade to Python3"
        uses: cclauss/Upgrade-to-Python3@master
      - name: Commit files
        run: |
              git config --local user.email "me@me.me"
              git config --local user.name "GitHub Action"
              git commit -m "Add changes" -a
      - name: Push changes
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'py3-addendum'
